#
# Basic secrets for Github runner
# Replace the values with your own secrets:
# echo -n 'admin' | base64        # YWRtaW4=
# etc.
#
apiVersion: v1
kind: Secret
metadata:
  name: githubrunner-secret
  namespace: githubrunner
  labels:
    app: trm-runner-1
type: Opaque
data:
  REPO_URL: xx_place_your_base64_secret_here_xx==
  ACCESS_TOKEN: xx_place_your_base64_secret_here_xx==
