apiVersion: v1
kind: Secret
metadata:
  name: sonar-secrets
  namespace: sonarqube
type: Opaque
data:
  POSTGRES_USER: xx_place_your_base64_secret_here_xx==
  POSTGRES_PASSWORD: xx_place_your_base64_secret_here_xx==
  SONAR_JDBC_USERNAME: xx_place_your_base64_secret_here_xx==
  SONAR_JDBC_PASSWORD: xx_place_your_base64_secret_here_xx==
  SONAR_ADMIN_PASSWORD: xx_place_your_base64_secret_here_xx==
