# postgres-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: sonarqube
spec:
  serviceName: "postgresql"               # headless-svc
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: postgres
          image: postgres:17.5            # latest stable version
          ports: [{ containerPort: 5432 }]
          env:
            - name: POSTGRES_DB
              value: sonarqube
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: sonar-secrets, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: sonar-secrets, key: POSTGRES_PASSWORD } }
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: manual
        volumeName: pgdata-pv             # hard link to PV
        accessModes: [ ReadWriteOnce ]
        resources:
          requests:
            storage: 10Gi
