#
# Copy this file to /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
#
# When the file is copied to the manifests directory, K3s will automatically apply it and create the Traefik configuration.
#
# In case, we need to force re-apply the configuration, we can delete the Traefik pod, and it will be recreated with the new configuration:
# k3s kubectl -n kube-system delete pod -l app.kubernetes.io/name=traefik
#
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik # must match the HelmChart name
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      podAnnotations:
        prometheus.io/port: "8082"
        prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"

    image:
      repository: rancher/mirrored-library-traefik
      tag: 3.3.6

    persistence:
      enabled: true
      existingClaim: traefik
      accessMode: ReadWriteOnce
      size: 128Mi
      path: /data

    additionalArguments:
      - "--certificatesresolvers.default.acme.email=dima@zaharov.info"
      - "--certificatesresolvers.default.acme.storage=/data/acme.json"
      - "--certificatesresolvers.default.acme.httpChallenge.entrypoint=web"
      - "--certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      #PROD- "--certificatesresolvers.default.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
    ports:
      web:
        port: 8000
        exposedPort: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        port: 8443
        exposedPort: 443
        protocol: TCP
